default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: <%= Rails.application.credentials[:adapter] %>
  encoding: <%= Rails.application.credentials[:encoding] %>
  database: <%= Rails.application.credentials[:database] %>
  pool: <%= Rails.application.credentials[:pool] %>
  username: <%= Rails.application.credentials[:username] %>
  password: <%= Rails.application.credentials[:password] %>
  timeout: <%= Rails.application.credentials[:timeout] %>
  port: <%= Rails.application.credentials[:port] %>
  host: <%= Rails.application.credentials[:host] %>


